### ISSUE TITLE
"Error: ..."

### ISSUE THREAD

**Issue by mohanzhang** [jpvillaisaza/licensor#14]
@jpvillaisaza this library really saved me this week! Thank you for putting it together. I wanted to contribute a bit of documentation to help others who might get the above error.

In my case, it was because `stack list-dependencies` was producing `<unknown>` versions. In `getDependencies`; this in turn can cause the parse to fail for certain dependencies, like

```
base-<unknown>
ghc-prim-<unknown>
integer-gmp-<unknown>
template-haskell-<unknown>
```

This will subsequently cause `sequence` to collapse the list of `[Maybe PackageIdentifier]` to `Nothing` instead of `Just [PackageIdentifier]`, resulting in that error message. I had to do a `filter isJust` on top of the parsed results to throw those out, and the rest worked beautifully :+1:

**Comment by jpvillaisaza** [comment]
@mohanzhang Thanks, Mohan! I'm very glad to read this.

Also, that "Error: ..." is really bad, it should say something useful. I'll work on it and try to find more ways to improve the program.

Which version of Stack are you using? I think I remember a Stack issue related to those unknown version numbers for GHC boot libraries (like base, ghc-prim, integer-gmp, and template-haskell), but I don't remember much about it right now.

**Comment by jpvillaisaza** [comment]
The unknown dependencies are no longer an issue, but I'm keeping this open to fix the error message.

**Comment by nomeata** [comment]
I also ran into `Error: ...` without further help, on an internal project. This is a Cabal-using project.

**Comment by jpvillaisaza** [comment]
@nomeata Thank you for reporting! And sorry about the useless error message. It currently only works if you have a `stack.yaml` file and Stack for listing the dependencies (which may not be an option for you).

I intend to update it to work with Cabal projects soon.

**Comment by nomeata** [comment]
In the end I found `cabal-plan license-report` sufficient.

**Comment by jpvillaisaza** [comment]
@nomeata Thanks for updating, I'll add `cabal-plan` to the README.
