### ISSUE TITLE
Collect all third party licenses

### ISSUE THREAD

**Issue by janjagusch** [jpvillaisaza/licensor#31]
Hi @jpvillaisaza, thanks for maintaining this package!

Licensor could become a very useful tool in the [conda-forge](https://conda-forge.org/) ecosystem for Haskell packages. What it is missing is to collect all license files, instead of just collecting the license types.

Context: in order to add a package to conda-forge, you need to provide a folder that contains all your dependencies' license files (can also be a single file, like in the [code-server-recipe](https://github.com/conda-forge/code-server-feedstock/blob/master/recipe/ThirdPartyNotices.vscode.txt)). I was hoping that the current output of licensor (summary of the license types) would be sufficient, [but unfortunately it is not](https://github.com/conda-forge/staged-recipes/pull/14802#discussion_r628948177).

Is collecting all license files a feature you consider in scope for licensor? It would help the packaging community tremendously and would allow us to add tools like [hadolint](https://github.com/conda-forge/staged-recipes/pull/14581) to conda-forge. Unfortunately I can't contribute this myself, as I don't know Haskell.

Would be great to know what you think about this. :)

**Comment by jpvillaisaza** [comment]
Hey @janjagusch! Thank you for opening this issue.

Yes, I think this feature is in scope for Licensor.

**Comment by janjagusch** [comment]
> Hey @janjagusch! Thank you for opening this issue.
> 
> Yes, I think this feature is in scope for Licensor.

Thanks for coming back to me so quickly. @jpvillaisaza!
Is this something you would like to work on yourself?

I can't help you with the coding unfortunately, but could help with reaching out to the conda-forge maintainers and asking whether the new format is sufficient, when you had something ready.

**Comment by jpvillaisaza** [comment]
@janjagusch Yes, this is something I would like to work on. I'm not sure when I can work on it, but I think I can come back to it later this week or during the weekend to get a better idea.

**Comment by jpvillaisaza** [comment]
Hey @janjagusch! I couldn't work on a good solution for this and will need more time for that, but I did work on a quick way to get the license files based on the current output of Licensor. I pushed the changes as work in progress. If you want to try it to see the output, see https://github.com/jpvillaisaza/licensor/pull/32. If you build that branch, you can then run the following:

```
licensor --quiet --licenses >> hadolint-licenses.md
```

This is what I got for `hadolint`:

[hadolint-licenses.md](https://github.com/jpvillaisaza/licensor/files/6490079/hadolint-licenses.md)

**Comment by janjagusch** [comment]
This look really great, thanks for your work! I'll pass this output to the conda-forge people to make sure it's sufficient.

**Comment by janjagusch** [comment]
@jpvillaisaza, I have used your branch to create a licenses file for licensor itself and added it to my conda-forge feedstock pull request. I have pinged the conda-forge maintainer again [here](https://github.com/conda-forge/staged-recipes/pull/14802#discussion_r634512540) to ask whether the format is sufficient now. Will report back once I have heard something new.

Thanks again for your work.

**Comment by jpvillaisaza** [comment]
@janjagusch Great, thanks!

**Comment by janjagusch** [comment]
hi @jpvillaisaza! good news: I got the confirmation that the new license format is sufficient for conda-forge. 😃 

you can read more about it [here](https://github.com/conda-forge/staged-recipes/pull/14802#discussion_r640071097).

So, once you release the new version, we can use licensor to bring a bunch of Haskell packages to conda-forge. 🎉

**Comment by jpvillaisaza** [comment]
@janjagusch Great, thanks for the update! I'll release a new version this weekend.

**Comment by jpvillaisaza** [comment]
@janjagusch I merged the changes and released a new version (0.5.0) which now includes the new command as described above. Thanks for the issue and for the follow-up comments to help with confirming everything! I'm going to close this issue, but feel free to reopen if there's anything missing or to open a new one if there are things to improve.
